### ISSUE TITLE
Dateirechte - Zip kann nicht heruntergeladen werden

### ISSUE THREAD

**Issue by operatorone** [trilobit-gmbh/contao-zipuploads-bundle#1]
Moin moin, ich habe in einem Contao 4.9.20 im Formular die Erweiterung  trilobit-gmbh/contao-zipuploads-bundle verwendet. Funktioniert auch alles prima, bis auf die Dateirechte des erzeugten Zip-Archivs. Die sind auf 600 gesetzt, statt z. B. 604 oder 750. Das hat zur Folge, dass über den Link in der E-Mail das Zip nicht heruntergeladen werden kann. Hat jemand eine Idee, wie ich diese Rechte anpassen könnte oder muss das in der Erweiterung geschehen? Danke im Voraus.

**Comment by denniserdmann** [comment]
@operatorone Ich habe das gleiche Problem. Hast du eine Lösung gefunden?

**Comment by operatorone** [comment]
Leider noch nicht. Ich habe mir einen Cronjob eingerichtet, der die Dateirechte jede Minute dementsprechend in dem Upload Verzeichnis anpasst. Ist nur ein Work Around und sicherlich noch keine endgültige und sinnvolle Lösung.
