### ISSUE TITLE
##form_autogeneretedZippedUploads## wird nicht ausgegeben

### ISSUE THREAD

**Issue by proplab** [trilobit-gmbh/contao-zipuploads-bundle#5]
Sehr coole Erweiterung. Aber:

Der Simple-Token ##form_autogeneretedZippedUploads## wird bei mir im Notification-Center nicht aufgelöst.
Ein E-Mail-Anhang kommt dadurch nicht zustande.
Es wird nur "##form_autogeneretedZippedUploads##" im Text ausgegeben.
Vielleicht gibt es ja noch einen Trick und der Token muss irgendwo registriert werden?

Contao 4.13.29
PHP 8.2.7,
contao-zipuploads-bundle 2.1.0
contao-fineuploader 3.4.3

**Comment by trilobit-gmbh** [comment]
https://community.contao.org/de/showthread.php?85617-trilobit-contao-zipuploads-bundle-E-Mail-Anhang

**Comment by trilobit-gmbh** [comment]
Vielen Dank für die Info.
Der Fehler liegt in der Reihenfolge, in der "processFormData" abgearbeitet wird. Hier ist leider das Bundle hinter das Notification-Center gerutscht. Das wird mit einem Update Mitte/Ende nächster Woche behoben werden.
LG Peter

**Comment by trilobit-gmbh** [comment]
see 2.1.1

**Comment by trilobit-gmbh** [comment]
@proplab Es ist ein Update verfügbar. Kannst Du bitte ergänzend testen ;-)

**Comment by proplab** [comment]
Gerade getestet. Funktioniert jetzt perfekt. Vielen Dank!
