### ISSUE TITLE
Der Cron für "ZIP-Dateien automatisch löschen" funktioniert nicht wie erwartet

### ISSUE THREAD

**Issue by proplab** [trilobit-gmbh/contao-zipuploads-bundle#7]
Ich habe den Wert für "ZIP-Dateien automatisch löschen" gesetzt.

![Unbenannt3](https://github.com/trilobit-gmbh/contao-zipuploads-bundle/assets/6940747/54988ae6-34b8-432d-a526-eb398c781fee)

Das Verzeichnis ist nicht öffentlich. Der Cron läuft offenbar minütlich. Es wird nicht gelöscht und im Log wird "Directory 'files/Bewerbungen' not found" ausgegeben.

![Unbenannt2](https://github.com/trilobit-gmbh/contao-zipuploads-bundle/assets/6940747/7ae8e7ea-0ed0-49f4-b6bb-f837fd51c4f3)

![Unbenannt](https://github.com/trilobit-gmbh/contao-zipuploads-bundle/assets/6940747/2f3bc07c-2363-43c9-bc4d-629073289e71)

Setze ich das Verzeichnis auf "öffentlich", verschwindet zwar die Fehlermeldung, gelöscht wird aber nicht.

Contao 4.13.29
PHP 8.2.7,
contao-zipuploads-bundle 2.1.1
contao-fineuploader 3.4.5

**Comment by trilobit-gmbh** [comment]
@proplab Neue Version 2.1.3 verfügbar, in der der Cron gefixed wurde. Bitte prüfen ;-) Danke.

**Comment by proplab** [comment]
Liebes trilobit-Team,

Herzlichen Dank erst mal für eure Bemühungen.
Ich bin leider heute erst zum Testen gekommen und irgendwie funktioniert es bei mir noch immer nicht.
Ich habe Version 2.1.3 installiert, alle Caches geleert etc.

Meine Einstellungen:
![Unbenannt2](https://github.com/trilobit-gmbh/contao-zipuploads-bundle/assets/6940747/bc6d6d0e-674c-466c-a11f-24997101c9fe)

Die Files sind größtenteils deutlich älter als 4 Wochen.
![Unbenannt3](https://github.com/trilobit-gmbh/contao-zipuploads-bundle/assets/6940747/8041c57c-1a6c-4215-b756-04983614d64e)

Im Log steht das:
![Unbenannt1](https://github.com/trilobit-gmbh/contao-zipuploads-bundle/assets/6940747/4d55a23b-9f3f-4765-9859-09c365333d97)
![Unbenannt4](https://github.com/trilobit-gmbh/contao-zipuploads-bundle/assets/6940747/8bc0a35f-ebc0-4dbd-80ed-b05ece32af23)

Kann es sein, dass die Einstellung nur für Files greift, die nach dem Update hochgeladen wurden?

**Comment by trilobit-gmbh** [comment]
Hallo @proplab ,
das Tool schaut beim Löschen neben dem Alter der Datei auch nach dem Muster des Dateinamens (so wie definiert). 
Nur Dateien, die in das Muster passen, werden auch gelöscht (das Tool geht nicht davon aus, dass das angegebene Verzeichnis exclusiv genutzt wird).
Wenn die alten Dateien noch in das Muster passen, dann sollten sie auch erkannt und ggf gelöscht werden. Vor dem letzten Update gab auch ein Problem mit den Dateiberechtigungen. Diese sind in der Zwischenzeit für die neuen ZIPS korrigiert; ggf sind diese aber noch nicht korrekt bei den alten Dateien, so dass diese nicht gelöscht werden (können). 

Kannst Du das bitte einmal prüfen (und z. B. mit einer normal hochgeladenen Datei vergleichen)?
Kannst Du einmal die Dateisyncronisierung laufen lassen (Es werden nur Dateien gefunden, die Contao auch kennt)?

Grüße
Peter
